export const GET_YOUTUBE_VIDEO_LIST_STARTED = 'GET_YOUTUBE_VIDEO_LIST_STARTED';
export const GET_YOUTUBE_VIDEO_LIST_SUCCESS = 'GET_YOUTUBE_VIDEO_LIST_SUCCESS';
export const GET_YOUTUBE_VIDEO_LIST_FAILURE = 'GET_YOUTUBE_VIDEO_LIST_FAILURE';
